### ISSUE TITLE
Swipe Not Working On Angular 10

### ISSUE THREAD

**Issue by longcharmroeun** [ralftar/ng-mat-carousel#20]
dependencies using:
`"dependencies": {
    "@angular-material-extensions/password-strength": "^6.0.0",
    "@angular/animations": "~10.0.5",
    "@angular/cdk": "^10.1.0",
    "@angular/common": "~10.0.5",
    "@angular/compiler": "~10.0.5",
    "@angular/core": "~10.0.5",
    "@angular/fire": "^6.0.2",
    "@angular/flex-layout": "^9.0.0-beta.31",
    "@angular/forms": "~10.0.5",
    "@angular/material": "^10.1.0",
    "@angular/platform-browser": "~10.0.5",
    "@angular/platform-browser-dynamic": "~10.0.5",
    "@angular/router": "~10.0.5",
    "bootstrap": "^4.5.0",
    "firebase": "^7.17.1",
    "hammerjs": "^2.0.8",
    "mat-video": "^2.8.1",
    "ng-mat-carousel": "^0.7.7",
    "ngx-auth-firebaseui": "^4.4.0",
    "password-strength": "github:angular-material-extensions/password-strength",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },`

**Comment by ralftar** [comment]
Remember to import hammerjs to your polyfill.

The demo is using angular 10, and should be working: https://ralftar.github.io/ng-mat-carousel/
